import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { muscleGroups, MuscleGroup } from '@/data/exercises';
import { Loader2, Download, Dumbbell, Calendar, Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface WorkoutDay {
  day: string;
  focus: string;
  exercises: {
    name: string;
    sets: number;
    reps: string;
    rest: string;
  }[];
}

interface GeneratedPlan {
  splitDays: number;
  goal: string;
  gender: string;
  targetMuscles: string[];
  schedule: WorkoutDay[];
}

export function WorkoutGenerator() {
  const [splitDays, setSplitDays] = useState<string>('4');
  const [gender, setGender] = useState<string>('');
  const [goal, setGoal] = useState<string>('strength');
  const [targetMuscles, setTargetMuscles] = useState<MuscleGroup[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedPlan, setGeneratedPlan] = useState<GeneratedPlan | null>(null);
  const { toast } = useToast();

  const toggleMuscle = (muscle: MuscleGroup) => {
    setTargetMuscles((prev) =>
      prev.includes(muscle) ? prev.filter((m) => m !== muscle) : [...prev, muscle]
    );
  };

  const generateWorkoutPlan = async () => {
    if (!gender) {
      toast({
        title: "Gender Required",
        description: "Please select your gender to generate a personalized plan.",
        variant: "destructive",
      });
      return;
    }

    setIsGenerating(true);
    
    try {
      const { data, error } = await supabase.functions.invoke('generate-workout', {
        body: {
          splitDays: parseInt(splitDays),
          gender,
          goal,
          targetMuscles,
        },
      });

      if (error) {
        throw new Error(error.message);
      }

      if (data.error) {
        throw new Error(data.error);
      }

      setGeneratedPlan({
        splitDays: parseInt(splitDays),
        goal,
        gender,
        targetMuscles: targetMuscles.length > 0 ? targetMuscles : ['All muscle groups'],
        schedule: data.schedule,
      });

      toast({
        title: "Workout Plan Generated!",
        description: "Your personalized workout plan is ready.",
      });

    } catch (error) {
      console.error("Error generating workout:", error);
      toast({
        title: "Generation Failed",
        description: error instanceof Error ? error.message : "Failed to generate workout plan. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPlan = () => {
    if (!generatedPlan) return;

    let content = `WORKOUT PLAN\n`;
    content += `${'='.repeat(50)}\n\n`;
    content += `Split: ${generatedPlan.splitDays}-Day Program\n`;
    content += `Gender: ${generatedPlan.gender.charAt(0).toUpperCase() + generatedPlan.gender.slice(1)}\n`;
    content += `Goal: ${generatedPlan.goal.charAt(0).toUpperCase() + generatedPlan.goal.slice(1)}\n`;
    content += `Target Muscles: ${generatedPlan.targetMuscles.join(', ')}\n\n`;
    content += `${'='.repeat(50)}\n\n`;

    generatedPlan.schedule.forEach((day) => {
      content += `${day.day}: ${day.focus}\n`;
      content += `${'-'.repeat(40)}\n`;
      day.exercises.forEach((exercise, index) => {
        content += `${index + 1}. ${exercise.name}\n`;
        content += `   Sets: ${exercise.sets} | Reps: ${exercise.reps} | Rest: ${exercise.rest}\n`;
      });
      content += `\n`;
    });

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by Workout Planner\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `workout-plan-${generatedPlan.splitDays}day-${generatedPlan.goal}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const groupedMuscles = muscleGroups.reduce(
    (acc, muscle) => {
      if (!acc[muscle.category]) {
        acc[muscle.category] = [];
      }
      acc[muscle.category].push(muscle);
      return acc;
    },
    {} as Record<string, typeof muscleGroups>
  );

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Dumbbell className="w-5 h-5" />
            Generate Your Workout Plan
          </CardTitle>
          <CardDescription>
            Customize your preferences to create a personalized workout split
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Split Days Selection */}
          <div className="space-y-3">
            <Label className="text-base font-medium flex items-center gap-2">
              <Calendar className="w-4 h-4" />
              How many days per week?
            </Label>
            <RadioGroup
              value={splitDays}
              onValueChange={setSplitDays}
              className="flex flex-wrap gap-3"
            >
              {['3', '4', '5', '6'].map((days) => (
                <div key={days} className="flex items-center space-x-2">
                  <RadioGroupItem value={days} id={`days-${days}`} />
                  <Label htmlFor={`days-${days}`} className="cursor-pointer">
                    {days} Days
                  </Label>
                </div>
              ))}
          </RadioGroup>
          </div>

          {/* Gender Selection */}
          <div className="space-y-3">
            <Label className="text-base font-medium">Gender</Label>
            <RadioGroup
              value={gender}
              onValueChange={setGender}
              className="flex flex-wrap gap-3"
            >
              {[
                { value: 'male', label: 'Male' },
                { value: 'female', label: 'Female' },
              ].map((g) => (
                <div key={g.value} className="flex items-center space-x-2">
                  <RadioGroupItem value={g.value} id={`gender-${g.value}`} />
                  <Label htmlFor={`gender-${g.value}`} className="cursor-pointer">
                    {g.label}
                  </Label>
                </div>
              ))}
            </RadioGroup>
          </div>

          {/* Goal Selection */}
          <div className="space-y-3">
            <Label className="text-base font-medium">Training Goal</Label>
            <RadioGroup
              value={goal}
              onValueChange={setGoal}
              className="flex flex-wrap gap-3"
            >
              {[
                { value: 'strength', label: 'Strength (Low reps, heavy weight)' },
                { value: 'hypertrophy', label: 'Muscle Growth (Moderate reps)' },
                { value: 'endurance', label: 'Endurance (High reps)' },
                { value: 'weight-loss', label: 'Lose Weight (High volume, short rest)' },
              ].map((g) => (
                <div key={g.value} className="flex items-center space-x-2">
                  <RadioGroupItem value={g.value} id={`goal-${g.value}`} />
                  <Label htmlFor={`goal-${g.value}`} className="cursor-pointer">
                    {g.label}
                  </Label>
                </div>
              ))}
            </RadioGroup>
          </div>

          {/* Target Muscles */}
          <div className="space-y-3">
            <Label className="text-base font-medium">
              Target Muscles (optional - leave empty for full body)
            </Label>
            {Object.entries(groupedMuscles).map(([category, muscles]) => (
              <div key={category}>
                <p className="text-xs text-muted-foreground mb-2">{category}</p>
                <div className="flex flex-wrap gap-2">
                  {muscles.map((muscle) => (
                    <div key={muscle.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={muscle.id}
                        checked={targetMuscles.includes(muscle.id)}
                        onCheckedChange={() => toggleMuscle(muscle.id)}
                      />
                      <Label htmlFor={muscle.id} className="cursor-pointer text-sm">
                        {muscle.name}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <Button
            onClick={generateWorkoutPlan}
            disabled={isGenerating}
            className="w-full"
            size="lg"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating Your Plan...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Workout Plan
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Generated Plan Display */}
      {generatedPlan && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>{generatedPlan.splitDays}-Day Workout Split</CardTitle>
                <CardDescription className="mt-1">
                  Goal: {generatedPlan.goal.charAt(0).toUpperCase() + generatedPlan.goal.slice(1)}
                </CardDescription>
              </div>
              <Button onClick={downloadPlan} variant="outline" size="sm">
                <Download className="w-4 h-4 mr-2" />
                Download Plan
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {generatedPlan.schedule.map((day) => (
                <Card key={day.day} className="bg-muted/50">
                  <CardHeader className="pb-2">
                    <Badge variant="outline" className="w-fit mb-1">
                      {day.day}
                    </Badge>
                    <CardTitle className="text-base">{day.focus}</CardTitle>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <ul className="space-y-2">
                      {day.exercises.map((exercise, index) => (
                        <li key={index} className="text-sm">
                          <p className="font-medium">{exercise.name}</p>
                          <p className="text-xs text-muted-foreground">
                            {exercise.sets} × {exercise.reps} • Rest: {exercise.rest}
                          </p>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
