import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { workoutTemplates, WorkoutTemplate } from '@/data/workoutTemplates';
import { Calendar, Dumbbell, Target, ChevronRight, Download, X } from 'lucide-react';

export function WorkoutTemplates() {
  const [selectedTemplate, setSelectedTemplate] = useState<WorkoutTemplate | null>(null);

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'beginner':
        return 'bg-green-500/10 text-green-600 border-green-500/20';
      case 'intermediate':
        return 'bg-yellow-500/10 text-yellow-600 border-yellow-500/20';
      case 'advanced':
        return 'bg-red-500/10 text-red-600 border-red-500/20';
      default:
        return '';
    }
  };

  const downloadTemplate = (template: WorkoutTemplate) => {
    let content = `${template.name.toUpperCase()}\n`;
    content += `${'='.repeat(50)}\n\n`;
    content += `Difficulty: ${template.difficulty.charAt(0).toUpperCase() + template.difficulty.slice(1)}\n`;
    content += `Days per Week: ${template.daysPerWeek}\n`;
    content += `Goal: ${template.goal}\n\n`;
    content += `${template.description}\n\n`;
    content += `${'='.repeat(50)}\n\n`;

    template.schedule.forEach((day) => {
      content += `${day.day}: ${day.focus}\n`;
      content += `${'-'.repeat(40)}\n`;
      day.exercises.forEach((exercise, index) => {
        content += `${index + 1}. ${exercise.name}\n`;
        content += `   Sets: ${exercise.sets} | Reps: ${exercise.reps} | Rest: ${exercise.rest}\n`;
      });
      content += `\n`;
    });

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by Musclepedia\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${template.id}-template.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {workoutTemplates.map((template) => (
          <Card
            key={template.id}
            className="cursor-pointer hover:shadow-lg transition-all hover:border-primary/50 group"
            onClick={() => setSelectedTemplate(template)}
          >
            <CardHeader>
              <div className="flex items-start justify-between">
                <Badge className={getDifficultyColor(template.difficulty)}>
                  {template.difficulty}
                </Badge>
                <ChevronRight className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors" />
              </div>
              <CardTitle className="text-lg mt-2">{template.name}</CardTitle>
              <CardDescription className="line-clamp-2">
                {template.description}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-3 text-sm text-muted-foreground">
                <div className="flex items-center gap-1">
                  <Calendar className="w-4 h-4" />
                  <span>{template.daysPerWeek} days/week</span>
                </div>
                <div className="flex items-center gap-1">
                  <Target className="w-4 h-4" />
                  <span>{template.goal}</span>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Dialog open={!!selectedTemplate} onOpenChange={() => setSelectedTemplate(null)}>
        <DialogContent className="max-w-4xl max-h-[85vh] overflow-y-auto">
          {selectedTemplate && (
            <>
              <DialogHeader>
                <div className="flex items-center justify-between pr-8">
                  <div>
                    <DialogTitle className="text-2xl">{selectedTemplate.name}</DialogTitle>
                    <DialogDescription className="mt-2">
                      {selectedTemplate.description}
                    </DialogDescription>
                  </div>
                </div>
                <div className="flex flex-wrap gap-3 pt-4">
                  <Badge className={getDifficultyColor(selectedTemplate.difficulty)}>
                    {selectedTemplate.difficulty}
                  </Badge>
                  <Badge variant="outline" className="flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    {selectedTemplate.daysPerWeek} days/week
                  </Badge>
                  <Badge variant="outline" className="flex items-center gap-1">
                    <Target className="w-3 h-3" />
                    {selectedTemplate.goal}
                  </Badge>
                </div>
              </DialogHeader>

              <div className="grid gap-4 mt-6 md:grid-cols-2">
                {selectedTemplate.schedule.map((day) => (
                  <Card key={day.day} className="bg-muted/50">
                    <CardHeader className="pb-2">
                      <Badge variant="outline" className="w-fit mb-1">
                        {day.day}
                      </Badge>
                      <CardTitle className="text-base flex items-center gap-2">
                        <Dumbbell className="w-4 h-4" />
                        {day.focus}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="pt-0">
                      <ul className="space-y-2">
                        {day.exercises.map((exercise, index) => (
                          <li key={index} className="text-sm">
                            <p className="font-medium">{exercise.name}</p>
                            <p className="text-xs text-muted-foreground">
                              {exercise.sets} × {exercise.reps} • Rest: {exercise.rest}
                            </p>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                ))}
              </div>

              <div className="flex justify-end gap-2 mt-6 pt-4 border-t">
                <Button variant="outline" onClick={() => setSelectedTemplate(null)}>
                  <X className="w-4 h-4 mr-2" />
                  Close
                </Button>
                <Button onClick={() => downloadTemplate(selectedTemplate)}>
                  <Download className="w-4 h-4 mr-2" />
                  Download Template
                </Button>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
